### ISSUE TITLE
Sent message but crashed klipper

### ISSUE THREAD

**Issue by CaryBab** [prd0000/push_notify#1]
I don't know what could cause this, but just in case you have run into it before I thought I'd check

Thanks

17:53:48
MCU 'mcu' shutdown: Timer too close
This often indicates the host computer is overloaded. Check
for other processes consuming excessive CPU time, high swap
usage, disk errors, overheating, unstable voltage, or
similar system problems on the host computer.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
17:53:48
echo: Nozzle heating stopped!
17:53:48
Klipper state: Shutdown
17:53:48
echo: Unloading filament...
17:53:48
echo: Pausing printing...
17:53:48
200 OK: {"status":1,"request":"50da1388-c5c6-447f-8041-09462e725209"}
17:53:43
Sending message: - Filament Change

**Comment by prd0000** [comment]
Timer too close usually caused by processor overloading. It means, the processor is not fast enough to do all the commands sent at the time required. 
Is it happen every time it sends the message?

**Comment by CaryBab** [comment]
I cleaned up the script some, comparing it with the samples on pushover
api.  And I found that putting an M400 after the last command in my config
before calling it (causes it to finish before going on ) that it doesn't
crash everytime.

**Comment by prd0000** [comment]
Thank you for your update. 

sending message via network does take time, and if it does it along with your klipper monitoring the printer, with a slow processor, combined with heavy UI, this error could occur.

**Comment by CaryBab** [comment]
So along with cleaning up the script to remove things that I don't use. I
also made it the last call in my macro, along with an M400 command before
it to make sure everything finished before calling it.  So far it has been
working with no crashes.  I run a FLsun SpeederPad on a SR, so the
speederpad is not what you would call a power processor.  But it sure is
great getting notifications on my phone in the middle of the night for a
filament change.  Your script is by far the simplest less bloated one I
have seen.  Thanks
