### ISSUE TITLE
Error in ntfy.sh or Pushover configuration

### ISSUE THREAD

**Issue by adrianobarrosmba** [prd0000/push_notify#2]
I'm configuring it as explained in the readme, but I get this error

"Internal error during connect: invalid syntax (fcm.py, line 10)"

**Comment by prd0000** [comment]
Can you put your configuration here, please? Also, can you explain what was your step when the error occur?

I will try to replicate them here.

**Comment by Auroch** [comment]
On Elegoo Neptune 4 Pro printer

```
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/mks/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/mks/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mks/klipper/klippy/extras/notify.py", line 10
    def __init__(self, config) -> None:
                               ^
SyntaxError: invalid syntax
```

**Comment by prd0000** [comment]
> On Elegoo Neptune 4 Pro printer
> 
> ```
> Unhandled exception during connect
> Traceback (most recent call last):
>   File "/home/mks/klipper/klippy/klippy.py", line 175, in _connect
>     self._read_config()
>   File "/home/mks/klipper/klippy/klippy.py", line 141, in _read_config
>     self.load_object(config, section_config.get_name(), None)
>   File "/home/mks/klipper/klippy/klippy.py", line 121, in load_object
>     mod = importlib.import_module('extras.' + module_name)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/mks/klipper/klippy/extras/notify.py", line 10
>     def __init__(self, config) -> None:
>                                ^
> SyntaxError: invalid syntax
> ```

Ah, it seems like spacing problem, that python wouldn't register the command. It seems it couldn't load the script.
Could you please redownload the script? 

Tell me if you still got problem.
