### ISSUE TITLE
Pushover Sound

### ISSUE THREAD

**Issue by Xierion** [prd0000/push_notify#3]
I use Pushover for multiple applications and would like a different sound for each one. I was able to modify the notift.py script to include sound selection:

`   def cmd_PUSH_NOTIFY(self, params):`
`        message = params.get('MSG', '')`
`        device_id = params.get('DEVICE', '')`
`        title = params.get('TITLE', '')`
**`        sound = params.get('SOUND', '')`**

and 

`        urllib.parse.urlencode({`
`            "token": self.api_key,`
`            "user": self.user_key,`
`            "device": device_id,`
`            "title": title,`
**`            "sound": sound,`**
`            "message": message`

Usage:
`PUSH_NOTIFY MSG=<message> [DEVICE=<device>] [TITLE=<title>] [SOUND=<sound>]`

**Comment by prd0000** [comment]
Thank you. Will update the script
